export const SET_LOADING              = 'SET_LOADING'
export const LOGS_ERROR               = 'LOGS_ERROR'
export const GET_BOOKINGS             = 'GET_BOOKINGS'
export const ADD_BOOKING              = 'ADD_BOOKING'
export const GET_DESKS                = 'GET_DESKS'
export const SELECTED_DESK            = 'SELECTED_DESK'
export const GET_DESK_BY_AREA_SILENT  = 'GET_DESK_BY_AREA_SILENT'
export const GET_DESK_BY_AREA_GENERAL = 'GET_DESK_BY_AREA_GENERAL'
export const ACTIVE_STEP              = 'ACTIVE_STEP'
export const GET_CHAIR_BY_DESK        = 'GET_CHAIR_BY_DESK'
export const SELECTED_SEAT            = 'SELECTED_SEAT'

