export const SET_LOADING  = 'SET_LOADING'
export const LOGS_ERROR   = 'LOGS_ERROR'
export const GET_BOOKINGS = 'GET_BOOKINGS'
export const ADD_BOOKING  = 'ADD_BOOKING'
export const GET_DESKS    = 'GET_DESKS'